spring:
  application:
    name: gateway
  cloud:
    gateway:
        routes:
          - id: user-service
            uri: lb://USER
            predicates:
            - Path=/users/**


          - id: hotel-service
            uri: lb://HOTEL
            predicates:
              - Path=/hotels/**

          - id: booking-service
            uri: lb://BOOKING
            predicates:
              - Path=/bookings/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

    register-with-eureka: true
    fetch-registry: true

  instance:
    hostname: localhost
    instance-id: localhost:${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90


server:
  port: 8080
