spring:
  application:
    name: hotel

  datasource:
    url: jdbc:postgresql://localhost:5432/hotel-infra
    username: postgres
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: # leave empty for local, set in prod
      timeout: 2000           # connection timeout in ms
      lettuce:
          pool:
            max-active: 10      # max connections in pool
            max-idle: 5         # max idle connections
            min-idle: 2         # min idle connections
            max-wait: 1000      # max wait for connection in ms


#eureka client setup
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

    register-with-eureka: true
    fetch-registry: true

  instance:
    hostname: localhost
    instance-id: localhost:${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90


server:
  port: 8082